### ISSUE TITLE
Tracebacks when installing and opening settings

### ISSUE THREAD

**Issue by nicksherman** [RafalBuchner/StemPlow#13]
I was able to install the new version 1.5 and the basic functionality seems to work, but I am also seeing some tracebacks. First, when I install it, I get this:
```
********************
Installing 'Stem Plow' report:
  Traceback (most recent call last):
      File "StemPlowTool.py", line 4, in <module>
      File "/Users/Nick/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/stemPlow/StemPlowSubscriber.py", line 880, in main
      File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 3949, in registerGlyphEditorSubscriber
      File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 3735, in addGlyphEditorSubscriber
      File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 3757, in _startGlyphEditorInstance
      File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 1484, in __init__
      File "/Users/Nick/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/stemPlow/StemPlowSubscriber.py", line 141, in build
      File "/Users/Nick/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/stemPlow/StemPlowSubscriber.py", line 202, in loadDefaults
      File "/Users/Nick/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/stemPlow/StemPlowSubscriber.py", line 480, in getFont
      File "lib/doodleFontWindow.pyc", line 400, in _get_document
    AttributeError: 'NoneType' object has no attribute 'document'
  
********************
Installing Extension 'Stem Plow': Done installing 'Stem Plow' (version 1.5.2).
```

Then, when I try to open the settings, I get this:
```
Traceback (most recent call last):
  File "StemPlowSettings.py", line 224, in <module>
  File "StemPlowSettings.py", line 220, in StemPlowSettingsWindowController
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/controllers.py", line 76, in __init__
  File "StemPlowSettings.py", line 120, in build
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/windows/window.py", line 361, in __init__
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/windows/base.py", line 75, in _initAdditions
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/windows/base.py", line 211, in setContent
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/tools/builder.py", line 80, in makeItem
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/tools/builder.py", line 129, in instantiateItem
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/forms/twoColumn.py", line 143, in __init__
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/containers/grid.py", line 240, in __init__
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/tools/builder.py", line 80, in makeItem
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/tools/builder.py", line 129, in instantiateItem
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/items/checkbox.py", line 153, in __init__
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/ezui/items/checkbox.py", line 170, in set
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/vanilla/vanillaCheckBox.py", line 92, in set
ValueError: depythonifying 'long long', got 'NoneType'

```

Perhaps relatedly, the message for installing the numpy and bezier packages didn't show up during the initial installation process. I restarted RoboFont though, and then the message about installing those packages showed up. After those were finally installed, things seem to finally work as expected.

**Comment by RafalBuchner** [comment]
I think now it should be resolved. Please, reopen this issue, if it is still there
