### ISSUE TITLE
Crash if overlapping coordinates in glyph

### ISSUE THREAD

**Issue by faebiou** [RafalBuchner/StemPlow#14]
Pretty much what the title says. Here's the traceback:
`Observer '<stemPlow.StemPlowSubscriber.StemPlowSubscriber object at 0x33d6ade20>' with '_roboFontCallback' failed: cannot convert float NaN to integer
Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 165, in callObserver_withMethod_forEvent_withInfo_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 1718, in _roboFontCallback
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 3421, in start
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 3438, in fire
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 1736, in _roboFontCoalescerCallback
  File "/Users/faebiou/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/stemPlow/StemPlowSubscriber.py", line 531, in glyphEditorDidMouseMove
  File "/Users/faebiou/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/stemPlow/StemPlowSubscriber.py", line 580, in updateText
  File "/Users/faebiou/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/stemPlow/StemPlowSubscriber.py", line 938, in findNames
ValueError: cannot convert float NaN to integer
`

**Comment by faebiou** [comment]
the "ignore overlaps" option solves this!
<img width="269" alt="Image" src="https://github.com/user-attachments/assets/2a43afbc-841b-4126-a9a3-384f4aaa928b" />
