### ISSUE TITLE
'StemPlowRuler' object has no attribute 'currentMeasurement1'

### ISSUE THREAD

**Issue by colinmford** [RafalBuchner/StemPlow#4]
Hi @RafalBuchner,

I'm getting a traceback:
```
Observer '<StemPlowSubscriber.StemPlowSubscriber object at 0x1405e26d0>' with '_roboFontCallback' failed: 'StemPlowRuler' object has no attribute 'currentMeasurement1'
Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 165, in callObserver_withMethod_forEvent_withInfo_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 1659, in _roboFontCallback
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 3320, in start
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 3337, in fire
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 1677, in _roboFontCoalescerCallback
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/StemPlowSubscriber.py", line 146, in glyphEditorDidScale
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/StemPlowSubscriber.py", line 418, in updateText
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/StemPlowSubscriber.py", line 785, in findNames
AttributeError: 'StemPlowRuler' object has no attribute 'currentMeasurement1'
```

It's strange... when I install StemPlow, it works well for a while, but then after using it for a while — maybe after closing and re-opening RF a few times? — I start getting this traceback while zooming in and out.

I can sometimes fix it by activating StemPlow with "f", and then the error goes away for a bit and then comes back. 

I don't have the time at the moment to pick through the code for a cause, but I would say probably the `currentMeasurement` variables need to be initialized with a default value on start up?

I often use Tal's Laser Measure as well, in case there is maybe some interaction happening there? Not sure this is a cause, but I can see you take some settings from it.

```
RoboFont 4.4b (build 2305191108)
Python 3.9.13
MacOS 13.4.1 (Darwin 22.5.0)
Processor i386 (x86_64)
```

Thanks,

Colin

**Comment by RafalBuchner** [comment]
yeah, I've had it several times as well. I'm trying to find the reason behind this. For now, I will update the version that initializes the variable as a class attribute set to `None`. I'm not closing this issue yet, just in case it will reappear in some other form. [(quick fix commit)](https://github.com/RafalBuchner/StemPlow/commit/aa8d5cc60f9c3d80b8e378f1588a9c66b70f8af8)
