### ISSUE TITLE
When used on a glyph consisting of only components it spams the python output.

### ISSUE THREAD

**Issue by JakobFangmeier** [RafalBuchner/StemPlow#7]
Looks like this and is especially annoying when the setting always is checked:

`Observer '<stemPlow.StemPlowSubscriber.StemPlowSubscriber object at 0x439bd1760>' with '_roboFontCallback' failed: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 165, in callObserver_withMethod_forEvent_withInfo_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 1718, in _roboFontCallback
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 3418, in start
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 3435, in fire
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.12/mojo/subscriber.py", line 1736, in _roboFontCoalescerCallback
  File "/Users/jf760871/Library/Application Support/RoboFont/plugins/StemPlow.roboFontExt/lib/stemPlow/StemPlowSubscriber.py", line 369, in glyphEditorDidMouseMove
TypeError: cannot unpack non-iterable NoneType object`

**Comment by RafalBuchner** [comment]
created fix, that potentially could be computationally heavy in case you have lots of components in glyph that you are working on. build 1.4.1
